const fs = require('fs');

const EN = {
  // App.tsx
  appTitle: 'AI Theme Studio',
  settings: 'Settings',
  appHeading: 'Catppuccin Theme Generator',
  appSubheading: 'Generate Stylus, LESS, and CSS themes from any website.',
  catppuccinProject: 'Catppuccin project',
  stylusExtension: 'Stylus extension',
  aiAccess: 'AI access',
  configured: 'Configured',
  needsApiKey: 'Needs API key',
  provider: 'Provider: ',
  fetcherKeys: 'Fetcher keys',
  configuredCount: '{count} configured',
  service: 'Service: ',
  openSettings: 'Open API & Model Settings',
  generateThemeHeading: 'Generate Theme',
  generateThemeDesc: 'Configure your keys in Settings, then provide a URL or folder snapshot to generate a Catppuccin UserStyle.',
  aiMappingDesc: 'AI-assisted selector mapping',
  aiMappingSubDesc: 'Improves role detection for buttons, alerts, badges, and similar UI selectors.',
  rerunSameCrawl: 'Re-run with same crawl',
  rerunTooltip: 'Reuse the last crawl without refetching',
  runCrawlFirst: 'Run a crawl first to enable quick re-run',
  lastCrawl: 'Last crawl: ',
  accentCoverage: 'Accent coverage',
  badgesCardsTables: 'Badges/Cards/Tables',
  alertsNotifications: 'Alerts/Notifications',
  fallbackWarning: 'The app will continue with direct HTTP fetch as a fallback.',
  paletteDiagnostics: 'Palette Diagnostics',
  downloadJsonUrl: 'Download profile JSON',
  runCrawlDownload: 'Run a crawl to enable download',
  cssVariables: 'CSS Variables:',
  inferredRoles: 'Inferred Roles:',
  warnings: 'Warnings',
  sampleRoles: 'Sample Roles',
  moreRoles: '+{count} more',
  madeWith: 'Made with Catppuccin |',
  github: 'GitHub',
  generatedBy: 'Generated by Github Copilot, Claude Code, Roo Code, OpenAI Codex, Gemini Code assistant',
  modelsUsed: 'Models:',
  settingsDesc: 'Configure AI provider, model, API keys, fetchers, and output fonts.',
  
  // AIConfig.tsx
  aiConfig: 'AI Configuration',
  save: 'Save',
  saved: 'Saved!',
  clear: 'Clear',
  aiProvider: 'AI Provider',
  aiModelLabel: 'AI Model (sorted by lowest known price)',
  chooseModel: 'Choose a model',
  loadingModel: 'Loading model catalog from provider API…',
  enterKeyToLoad: 'Enter API key to load models',
  enterValidBaseUrl: 'Enter a valid base URL (https://...) to load models',
  failedToLoadModels: 'Failed to load provider models',
  apiKeyLabel: '{provider} API Key',
  enterApiKey: 'Enter your {provider} API key',
  securityNote: 'Security: Your API key is stored locally and only sent to the selected provider.',
  ollamaBaseUrl: 'Ollama Cloud Base URL',
  openaiBaseUrl: 'OpenAI-Compatible Base URL',
  ollamaWarning: 'Default uses Ollama Cloud (`https://ollama.com`). On localhost, requests are sent through the local `/ollama` proxy to avoid browser CORS blocking.',
  openaiWarning: 'Accepts any OpenAI-compatible endpoint. `/v1` is added automatically when missing.',
  openRouterDesc: 'Catalog + pricing from API',
  openaiDesc: 'Custom /v1 endpoint support',
  ollamaDesc: 'Cloud API only (no localhost dependency)',
  
  // FetcherConfig.tsx
  fetcherConfigHeading: 'Web Fetcher Configuration',
  saveConfig: 'Save Config',
  fetcherNote: 'API-based fetchers extract website content including HTML, CSS, and colors. Jina Reader is free and always available. For best results with JavaScript-heavy sites, configure Firecrawl or ScrapingBee.',
  preferredFetcher: 'Preferred Fetcher Service',
  servicePriority: 'Service Priority Chain',
  servicePriorityDesc: 'If the preferred service fails, the next available service will be used automatically.',
  apiKeyRequired: 'API key required ↓',
  apiKeysOptional: 'API Keys (Optional)',
  apiKeysNote: 'Security Note: API keys are stored locally in your browser using base64 encoding. They are only sent to their respective services.',
  
  // ThemePreview.tsx
  noThemeGenerated: 'No theme generated yet. Enter a URL above to get started!',
  generatedThemeHeading: 'Generated UserStyle Theme',
  generatedFrom: 'Generated from: ',
  themeSupportsFlavors: 'This theme supports all 4 Catppuccin flavors with light/dark mode detection',
  downloadUserStyle: 'Download UserStyle (.less)',
  copyClipboard: 'Copy to Clipboard',
  copied: 'Copied!',
  catppuccinFlavors: 'Catppuccin Flavors',
  codePreview: 'UserStyle Code Preview',
  howToUse: 'How to Use',
  instructions1: 'Install a UserStyle manager (Stylus for Chrome/Firefox, or Cascadea for Safari)',
  instructions2: 'Download the .less file above',
  instructions3: 'In your UserStyle manager, create a new style and paste the code',
  instructions4: 'The theme will automatically adapt to light/dark mode',
  instructions5: 'Choose your preferred accent color in the UserStyle settings',
  generationInfo: 'Generation Info',
  source: 'Source: ',
  aiModelUsed: 'AI Model: ',
  generatedAt: 'Generated: ',
  accentColorsDetected: 'Accent Colors Detected: ',
  oldFormatWarning: 'Old theme format detected. Please regenerate the theme.',
  
  // DeepAnalysisControls.tsx
  deepAnalysisMode: 'Deep Analysis Mode',
  deepAnalysisDesc: 'AI-powered precision mapping with CSS variables, SVGs, and design system detection',
  flavor: 'Flavor',
  defaultFlavor: 'Default Flavor',
  usersChangeFlavor: 'Users can change in Stylus UI after install',
  mainAccent: 'Main Accent',
  defaultAccent: 'Default Accent',
  usersChangeAccent: 'Users can switch between all 14 accents',
  v3Generator: 'V3 Generator',
  v3GeneratorDesc: 'Dynamic multi-flavor support – users can change flavors and accents in Stylus UI after install!',
  v3AdvancedOptions: 'V3 Advanced Options',
  cascadingGradients: 'Cascading Gradients',
  cascadingGradientsDesc: '3-level gradient system with analogous color harmony (±72° hue)',
  gradientCoverage: 'Gradient Coverage',
  deepAnalysisInfo: 'Deep Analysis provides superior theme quality by analyzing CSS variables, SVG icons, and design system patterns. Best for modern websites with design systems.',
  v3Info: 'V3 Generator creates themes with dynamic flavor/accent switching – one theme, 56 combinations (4 flavors × 14 accents)!',
  
  // ThinkingProcess.tsx
  aiProcessingSteps: 'AI Processing Steps',
  output: 'Output: ',
  processingCompleted: 'All processing steps completed successfully!',
  processingFailed: 'Processing failed. Please check the error details above.',
  resetAndTryAgain: 'Reset and Try Again'
};

const ZHTW = Object.fromEntries(Object.entries(EN).map(([k,v]) => [k, `${v} (zh-TW)`]));
const ZHCN = Object.fromEntries(Object.entries(EN).map(([k,v]) => [k, `${v} (zh-CN)`]));
const ES = Object.fromEntries(Object.entries(EN).map(([k,v]) => [k, `${v} (es)`]));
const FR = Object.fromEntries(Object.entries(EN).map(([k,v]) => [k, `${v} (fr)`]));
const JA = Object.fromEntries(Object.entries(EN).map(([k,v]) => [k, `${v} (ja)`]));

let content = fs.readFileSync('src/i18n.ts', 'utf8');

// Insert EN
const enKeys = Object.entries(EN).map(([k,v]) => `  ${k}: ${JSON.stringify(v)},`).join('\n');
content = content.replace(/nerdFontsGroup: 'Nerd Fonts',/, `nerdFontsGroup: 'Nerd Fonts',\n${enKeys}`);

// Insert ZHTW
const zhtwKeys = Object.entries(ZHTW).map(([k,v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n');
content = content.replace(/nerdFontsGroup: 'Nerd Fonts',\n  },(\s+)'zh-CN':/, `nerdFontsGroup: 'Nerd Fonts',\n${zhtwKeys}\n  },$1'zh-CN':`);

// Insert ZHCN
const zhcnKeys = Object.entries(ZHCN).map(([k,v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n');
content = content.replace(/nerdFontsGroup: 'Nerd Fonts',\n  },(\s+)es:/, `nerdFontsGroup: 'Nerd Fonts',\n${zhcnKeys}\n  },$1es:`);

// Insert ES
const esKeys = Object.entries(ES).map(([k,v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n');
content = content.replace(/nerdFontsGroup: 'Nerd Fonts',\n  },(\s+)fr:/, `nerdFontsGroup: 'Nerd Fonts',\n${esKeys}\n  },$1fr:`);

// Insert FR
const frKeys = Object.entries(FR).map(([k,v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n');
content = content.replace(/nerdFontsGroup: 'Nerd Fonts',\n  },(\s+)ja:/, `nerdFontsGroup: 'Nerd Fonts',\n${frKeys}\n  },$1ja:`);

// Insert JA
const jaKeys = Object.entries(JA).map(([k,v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n');
content = content.replace(/nerdFontsGroup: 'Nerd Fonts',\n  },\n};/, `nerdFontsGroup: 'Nerd Fonts',\n${jaKeys}\n  },\n};`);

fs.writeFileSync('src/i18n.ts', content);
console.log('Keys injected. Now replacing in components...');

